
services:

  db:
    container_name: postgres
    image: postgres:18
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: izeta
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kalaka
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - 5432:5432


  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  db-data: