
services:

  db:
    container_name: postgres
    image: postgres:18
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_TEST_DATABASE: ${POSTGRES_TEST_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}


  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  db-data: